# Generated by Django 2.2.16 on 2022-04-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', error_messages={'validators': 'Выбрана несуществующая роль'}, max_length=10, verbose_name='Роль'),
        ),
    ]
