# Generated by Django 2.2.16 on 2022-04-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='reviews.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='reviews.Genre'),
            preserve_default=False,
        ),
    ]
