# Generated by Django 2.2.16 on 2022-04-02 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220401_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='item_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
